remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: icanhaspii BugForge STUFF
description: A very special thank-you to <a>https://b1g-b33f.github.io</> for allowing me to use his framework as a guide.
